### ISSUE TITLE
Map format conversion (import external maps)

### ISSUE THREAD

**Issue by zbzhu99** [bark-simulator/bark#408]
1. I am curious how to convert the map downloaded from openstreetmap.com into the required opendrive format?
2. I noticed that some maps in the INTERACTION dataset are used in BARK and those maps were originally in lanelet2 format. How are they converted to opendrive format?

**Comment by klemense1** [comment]
Unfortunately, there is no straight way from generating opendrive from openstreetmap, as openstreetmap does not necessarily contain all the information. You can use it as a base to generate lanelet2 files, have a look to the documentation of lanelet.

We converted the lanelet files to opendrive by basically modelling the whole map again in opendrive using some commercial tool. That's quite tedious, which is why we haven't done it for all the Interaction dataset maps yet.

**Comment by zbzhu99** [comment]
Thank you~
